In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [3]:
#Load the Iris Dataset
iris = load_iris()

X = iris.data
feature_names = iris.feature_names

print("Dataset Shape:", X.shape)
print("Features:", feature_names)

Dataset Shape: (150, 4)
Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
print("First 10 rows of Iris Dataset:")
print(X[:10])

First 10 rows of Iris Dataset:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [6]:
#Calculate Sum
total = np.sum(X, axis=0)

print("Sum of each feature:")
print(total)

Sum of each feature:
[876.5 458.6 563.7 179.9]


In [7]:
#Calculate Mean
mean = np.mean(X, axis=0)

print("Mean of each feature:")
print(mean)

Mean of each feature:
[5.84333333 3.05733333 3.758      1.19933333]


In [8]:
#Calculate Median
median = np.median(X, axis=0)

print("Median of each feature:")
print(median)

Median of each feature:
[5.8  3.   4.35 1.3 ]


In [9]:
#Calculate Minimum and Maximum
minimum = np.min(X, axis=0)
maximum = np.max(X, axis=0)

print("Minimum values:")
print(minimum)

print("\nMaximum values:")
print(maximum)

Minimum values:
[4.3 2.  1.  0.1]

Maximum values:
[7.9 4.4 6.9 2.5]


In [10]:
#Calculate Standard Deviation
std = np.std(X, axis=0)

print("Standard deviation:")
print(std)

Standard deviation:
[0.82530129 0.43441097 1.75940407 0.75969263]


In [11]:
#Calculate Variance
variance = np.var(X, axis=0)

print("Variance:")
print(variance)

Variance:
[0.68112222 0.18871289 3.09550267 0.57713289]


In [14]:
#Compare Using axis=0 
print("Mean using axis=0:")
print(np.mean(X, axis=0))

Mean using axis=0:
[5.84333333 3.05733333 3.758      1.19933333]


In [15]:
#Axis = 1
print("Mean of first 10 samples using axis=1:")
print(np.mean(X[:10], axis=1))


Mean of first 10 samples using axis=1:
[2.55  2.375 2.35  2.35  2.55  2.85  2.425 2.525 2.225 2.4  ]


In [16]:
#Create a Statistical Summary
print("Statistical Summary")

print("Mean:", np.mean(X, axis=0))
print("Median:", np.median(X, axis=0))
print("Minimum:", np.min(X, axis=0))
print("Maximum:", np.max(X, axis=0))
print("Standard Deviation:", np.std(X, axis=0))
print("Variance:", np.var(X, axis=0))
print("Sum:", np.sum(X, axis=0))

Statistical Summary
Mean: [5.84333333 3.05733333 3.758      1.19933333]
Median: [5.8  3.   4.35 1.3 ]
Minimum: [4.3 2.  1.  0.1]
Maximum: [7.9 4.4 6.9 2.5]
Standard Deviation: [0.82530129 0.43441097 1.75940407 0.75969263]
Variance: [0.68112222 0.18871289 3.09550267 0.57713289]
Sum: [876.5 458.6 563.7 179.9]
